version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - db
    command: >
      sh -c "composer install &&
             php artisan migrate --force &&
             php artisan db:seed --class=UserSeeder --force &&
             php-fpm"

  web:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  nuxt:
    build:
      context: ../todo-nuxt3a
      dockerfile: Dockerfile
    container_name: nuxt_app
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ../todo-nuxt3a:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge